### PR TITLE
Prototype 24

### PR DESCRIPTION
**Pull request by steven-borthwick**
Changes to NI record/help number added

### CODE REVIEW

**Comment by codeArtist2015** [comment]
@steven-borthwick This is now merged now and should be available online in 5 mins.

**Comment by codeArtist2015** [comment]
@steven-borthwick I am likeing the new sidebar with telephone number.

**Comment by steven-borthwick** [comment]
Ha thanks! I like how in the new version you can copy the folder of a
prototype, rename and it just works!

On Wed, Nov 25, 2015 at 4:04 PM, codeArtist2015 <notifications@github.com>
wrote:

> @steven-borthwick <https://github.com/steven-borthwick> I am likeing the
> new sidebar with telephone number.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeArtist2015/nisp-prototype/pull/14#issuecomment-159655555>
> .
>



-- 
Steven Borthwick | Interaction Designer | NI & State Pensions | Department
for Work and Pensions | Newcastle upon Tyne | 07870 469540

**Comment by codeArtist2015** [comment]
@steven-borthwick That's great, I am happy that it helped you a bit in your daily routine. 

Much appreciate it.

**Pull request merged**
